### ISSUE TITLE
Super Punch

### ISSUE THREAD

**Issue by Albert** [Albert/VR-Design-Haikus#3]
Make full world completely black (i think you remove skybox and camera bg color should be black)
punchSensor.cs
  have a Vector3<List> as a private int
  each frame add controller's current position (something like myList.Add(transform.position))
  if list gets to 5 or more frames in length, remove the first element in the list (i think it's myList.removeAt(0))
  if the vector3 distance between last el in list and first el in list is 0.1 units or greater, activate effect... Play w/ that variable to make something that feels about right...

effect is
  a thunderclap sound effect plays (freesound.org, some sort of thunderclap w/ a "creative commons" license)
  black world pops to white for 5 frames, then back to black

**Comment by andpeterson** [comment]
Interesting concept, sounds fun

**Comment by andpeterson** [comment]
There are two ways to do this. One will keep an array list you are saying and will compare the beginning and the end. This would possibly lead to a more accurate magnitude though taking the last position and comparing that to the current position gives you the ability to divide them by time.deltaTime giving you a possibly less accurate velocity but will give you the actual speed rather than 'relative speed'

Maybe there may be a way to get the best of both worlds... to be looked into later

**Comment by andpeterson** [comment]
Finished base requirements

**Comment by Albert** [comment]
Hah, perfect.  This feels great.
